# HabitEngineer Website Configuration
# シンプルで安定性重視の設定

baseURL = 'https://habitengineer.com/'
languageCode = 'ja'
title = 'HabitEngineer'
defaultContentLanguage = 'ja'

# 日本語設定
[languages.ja]
  languageName = '日本語'
  weight = 1

# サイト全体のパラメータ
[params]
  description = 'IT技術で習慣を定着させる - AIとNotionでビジネスの課題を解決'
  author = 'HabitEngineer'
  
  # 会社情報
  companyName = 'HabitEngineer'
  companyNameEn = 'Habit Engineer'
  tagline = '習慣 × エンジニア'
  
  # カラーテーマ（桜ピンク）
  primaryColor = '#FFC0CB'
  
  # Copyright
  copyright = '© 2025 HabitEngineer. All rights reserved.'

# メニュー設定
[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'HabitEngineerとは'
    url = '/'
    weight = 10
    
  [[menu.main]]
    identifier = 'services'
    name = 'サービス'
    url = '/services/'
    weight = 20
    
  [[menu.main]]
    identifier = 'products'
    name = '開発製品'
    url = '/products/'
    weight = 25
    
  [[menu.main]]
    identifier = 'results'
    name = '実績'
    url = '/results/'
    weight = 30
    
  [[menu.main]]
    identifier = 'about'
    name = '事業者情報'
    url = '/about/'
    weight = 40
    
  [[menu.main]]
    identifier = 'blog'
    name = 'ブログ'
    url = '/blog/'
    weight = 50

# パーマリンク設定（シンプルなURL構造）
[permalinks]
  blog = '/blog/:filename/'

# マークアップ設定
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false  # セキュリティ重視
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    style = 'monokai'

# 出力設定
[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML', 'RSS']

# RSS設定
[rssLimit]
  limit = 20

# サイトマップ設定
[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

# セキュリティ設定
[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['GET', 'POST']
    urls = ['.*']