title: HabitEngineer
description: 良い習慣をIT技術で定着させる専門家
url: https://habitengineer.com
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Collections
collections:
  cases:
    output: true
    permalink: /results/cases/:name/
  products:
    output: true
    permalink: /results/products/:name/

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "cases"
    values:
      layout: "results"
  - scope:
      path: ""
      type: "products"
    values:
      layout: "results"